export const REGION = 'ap-southeast-2'
export const ACCESS_KEY_ID = 'AKIAQ3EGTZ5MREDLP267'
export const SECRET_KEY_ID = 'eQdcOudcXtJXlRAKYChCQGK3uh+BTt4I14iucbQc'
export const BUCKET_NAME = 'chaochao-bucket'
export const API_URL = 'https://chaochao-bucket.s3-ap-southeast-2.amazonaws.com'
